project: https://github.com/AudioReach/audioreach-graphmgr

branches:
  publish:
    modes:
      blocking:
        headers:
          - service/inc/public/agm/agm_api.h
abi_checks:
  - path: usr/bin/libagm.so