name: Qualcomm Preflight Checks

on:
  pull_request:
    branches: [ publish ]
  push:
    branches: [ publish ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  qcom-preflight-checks:
    uses: Audioreach/audioreach-workflows/.github/workflows/qcom-preflight-checks.yml@publish
    secrets: inherit
