name: Qualcomm Preflight Checks

on:
  pull_request_target:
    branches: [ master ci_test]
  push:
    branches: [ master ci_test]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  qcom-preflight-checks:
    uses: AudioReach/audioreach-workflows/.github/workflows/qcom-preflight-checks.yml@stg
    secrets: inherit
